name: Goncharov. Postman Collection WorkFlow

on:
  push:
    branches:
      - main
jobs:
  fun_with_newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
         node-version: '18'

    - name: Install newman and HTML reporter
      run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
    - name: Run tests
      run: newman run src/FinalBackendHWGoncharov.postman_collection -e src/OnlineSchool.BackendHW.postman_environment.json -r cli,htmlextra,junit
