name: Goncharov. Postman Collection WorkFlow

on:
  push:
    branches:
      - main
jobs:
  fun_with_newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
         node-version: '18'

    - name: Install newman and HTML reporter
      run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
    - name: Run tests
      run: newman run src/Lesson3Collection.postman_collection.json -e src/Lesson3env.BackendHW.postman_environment.json -r cli,htmlextra,junit
    - name: Checkout to gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Copy report to the gh-pages branch
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: newman
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Deploy the report from the gh-pages branch to the website
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: newman
